version: "3"
services:
  node-express:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
     - mongo
    
  mongo:
    image: mongo
    env_file:
      - ./.env
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: